### ISSUE TITLE
output option

### ISSUE THREAD

**Issue by mausotog** [se-passau/jdime#15]
Hi,
I don´t understand if there is a right way to use the output option.
If I run it with just a path, like this:
JDime --mode structured --output somePath/ somePath/versionLeft.java somePath/versionBase.java somePath/versionRight.java

I get this error:
Logging configuration file JDimeLogging.properties does not exist. Falling back to defaults.
JDime [18:23:05] WARNING: JDime.properties can not be used as a config file as it does not exist. 
The output file or directory exists. Use -f to force overwriting.

If I add the "-f" argument as indicated in the message like this:
JDime --mode structured -f --output somePath/ somePath/versionLeft.java somePath/versionBase.java somePath/versionRight.java

I get this error:
Logging configuration file JDimeLogging.properties does not exist. Falling back to defaults.
JDime [18:30:29] WARNING: JDime.properties can not be used as a config file as it does not exist. 
The output must be a file when merging files.

If I add an output file as indicated in the message like this (with or without the "-f" I get the same error):

JDime --mode structured -f --output somePath/outputFijle.java somePath/versionLeft.java somePath/versionBase.java somePath/versionRight.java

I get this error:
Logging configuration file JDimeLogging.properties does not exist. Falling back to defaults.
JDime [18:31:41] WARNING: JDime.properties can not be used as a config file as it does not exist. 
JDime [18:31:41] SEVERE: Uncaught exception. 
java.lang.IllegalArgumentException: File 'somePath/outputFile.java' does not exist.
	at de.fosd.jdime.artifact.file.FileArtifact.<init>(FileArtifact.java:205)
	at de.fosd.jdime.artifact.file.FileArtifact.<init>(FileArtifact.java:181)
	at de.fosd.jdime.config.merge.MergeContext.configInputOutput(MergeContext.java:686)
	at de.fosd.jdime.config.merge.MergeContext.configureFrom(MergeContext.java:333)
	at de.fosd.jdime.Main.parseCommandLineArgs(Main.java:368)
	at de.fosd.jdime.Main.run(Main.java:139)
	at de.fosd.jdime.Main.main(Main.java:113)

So, what's the correct way to use the output option?
Thanks!

PS: I'm using java version "1.8.0_131"

**Comment by mausotog** [comment]
Also, if I use the unstructured or autotuning mode. It just fails. Am I doing something wrong?
Running:
JDime --mode unstructured -f --output somePath/outputFijle.java somePath/versionLeft.java somePath/versionBase.java somePath/versionRight.java

I get error:
Logging configuration file JDimeLogging.properties does not exist. Falling back to defaults.
JDime [23:24:28] WARNING: JDime.properties can not be used as a config file as it does not exist. 
Invalid mode 'unstructured'.

Same thing happens with autotuning

**Comment by GSeibt** [comment]
Hey,

I am assuming that you are using the develop branch of this repository and that JDime is built using `./gradlew installDist`. 

First of all you should run JDime using the appropriate (Windows / Linux) script in `build/install/JDime/bin/` and that directory should be your working directory at the time. This will get rid of the `JDimeLogging.properties` and `JDime.properties` warnings. 

> Invalid mode 'unstructured'.  

The problem here is that the README is outdated. Some time ago we removed all aliases like 'unstructured'. `JDime --help` correctly indicates the currently available modes. 'unstructured' is equal to 'linebased' and 'autotuning' was replaced by specifying a comma separated list of modes.

I will have to look into your first problem tomorrow, we recently had a problem with input / output files and this might be a regression.

**Comment by GSeibt** [comment]
Ok - so I usually user JDime with --pretend which does not require an output file / directory. That is why I never noticed this issue. 

First of all: When merging files -o has to point to a file and when merging directories it has to point to a directory. The problem was that you would have had to set -f and create an empty file to overwrite for it to work. That is obviously not the way that option was intended. 

I have now done some work on our FileArtifact class and you should now be able to use -o in a more intuitive way. The first rule still holds but if the file given with -o does not exist it will be created after the merge is finished. 

If you notice any problems don't hesitate to contact me.
